fields_under_root: true
fields:
  environment: ${FILEBEAT_ENV}
  region: ${FILEBEAT_REGION}
  clientId: FUSE

filebeat.inputs:
  - type: log
    paths:
      - /opt/tomcat/logs/elk.log
    fields_under_root: true
    fields:
      document_type: tomcat
      eventType: application
      status: atomic
      component: ${APPLICATION_COMPONENT}
      componentInstance: ${APPLICATION_COMPONENT_INSTANCE}
      componentVersion: 1.0.0
    multiline.pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}|^[a-zA-z]{3,4} [0-9]{2}, [0-9]{4} [0-9]{1,2}:[0-9]{2}:[0-9]{2} [a-zA-z]{2}
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["${LOGSTASH_HOST}"]