version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  config-server:
    build: config-server
    ports:
      - "8888:8888"

  product:
    build: product
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    deploy:
      restart_policy:
        condition: on-failure
    ports:
        - "8081:8080"
    depends_on:
      - config-server
      - mongo

  order:
    build: order
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
    deploy:
      restart_policy:
        condition: on-failure
    ports:
        - "8082:8080"
    depends_on:
      - config-server
      - mongo
      - product