version: '3'

services:
  mongo:
    image: mongo
    ports:
        - "27017:27017"
  product:
    build: product
    ports:
        - "8081:8080"
    depends_on:
      - mongo
  order:
    build: order
    ports:
        - "8082:8080"
    depends_on:
      - mongo
      - product