version: "3"

services:
    elasticsearch: &networks
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            discovery.type: single-node
        networks:
            - default
            - elk
    kibana:
        <<: *networks
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.11.1
        ports:
            - 5601:5601
    logstash:
        <<: *networks
        container_name: logstash
        image: docker.elastic.co/logstash/logstash:7.11.1
        ports:
            - 5044:5044
        volumes:
            - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

networks:
    elk:
        external:
            name: elk # docker network create -d bridge elk